# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Settings specified in this file will override any Gradle settings
# configured through the IDE.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# The Gradle daemon aims to improve build performance
org.gradle.daemon=true

# Enable caching build artifacts
org.gradle.caching=true

# When configured, Gradle will run in parallel mode.
# This option should only be used with decoupled projects.
org.gradle.parallel=true

# When configured, Gradle will use a maximum of the specified number of workers.
org.gradle.workers.max=4

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx4g -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Enable new desugaring in Android Plugin
# Read more: https://developer.android.com/studio/releases/gradle-plugin#4.0-features
android.useAndroidX=true
android.enableJetifier=true

# Use this property to enable support for legacy multi-dex architecture
android.enableDexingArtifactTransform.desugaring=false

# Use this property to enable the Hermes JS engine
hermesEnabled=true

# Use this property to specify which architecture you want to build.
# You can also override it from the CLI using
# ./gradlew <task> -PreactNativeArchitectures=x86_64
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Explicitly set build features
android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.buildconfig=false
android.defaults.buildfeatures.renderscript=false
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false
